/**
 * AUTO-GENERATED by scripts/apply-brief.mjs — do not edit manually.
 * Source brief: brief.example.json
 * Generated: 2026-07-05T09:06:36.406Z
 */
import type { SiteConfig } from '~/config/site.types'

export const siteConfig = {
  "businessName": "Summit Plumbing Co.",
  "industry": "plumber",
  "tagline": "Licensed, insured, and available 24/7 for emergency repairs.",
  "phone": "(555) 123-4567",
  "email": "hello@summitplumbing.example",
  "address": "123 Main Street, Denver, CO 80202",
  "hours": "Mon–Fri 7am–6pm · Sat 8am–2pm · 24/7 emergency line",
  "designPreset": "trustworthy-blue",
  "navigation": [
    {
      "label": "Home",
      "href": "/"
    },
    {
      "label": "Services",
      "href": "/services"
    },
    {
      "label": "About",
      "href": "/about"
    },
    {
      "label": "Contact",
      "href": "/contact"
    }
  ],
  "primaryCta": {
    "label": "Get a free quote",
    "href": "/contact"
  },
  "secondaryCta": {
    "label": "Call now",
    "href": "tel:+15551234567"
  },
  "seo": {
    "title": "Summit Plumbing Co. | Denver Emergency Plumber",
    "description": "Licensed Denver plumbers for leaks, drains, water heaters, and 24/7 emergency service.",
    "keywords": "plumber Denver, emergency plumber, drain cleaning"
  },
  "services": [
    {
      "slug": "emergency-plumbing",
      "title": "Emergency plumbing",
      "description": "Burst pipes, major leaks, and backups handled fast — day or night."
    },
    {
      "slug": "drain-cleaning",
      "title": "Drain cleaning",
      "description": "Clear slow or clogged drains with professional equipment."
    }
  ],
  "reviews": [
    {
      "quote": "They arrived within an hour and fixed our burst pipe.",
      "author": "Maria L.",
      "rating": 5
    }
  ],
  "trustBadges": [
    {
      "label": "Licensed & insured",
      "value": "Fully licensed"
    },
    {
      "label": "Average rating",
      "value": "4.9 ★"
    }
  ],
  "stats": [
    {
      "label": "Jobs completed",
      "value": "1,000+"
    },
    {
      "label": "Satisfaction rate",
      "value": "98%"
    }
  ],
  "team": [],
  "faqs": [],
  "serviceAreas": []
} satisfies SiteConfig
