#!/usr/bin/env node
/**
 * Apply brief.json → site.config.ts + harness report.
 *
 * Usage:
 *   node scripts/apply-brief.mjs
 *   node scripts/apply-brief.mjs --brief ./path/to/brief.json
 *   node scripts/apply-brief.mjs --if-present
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import {
  loadRegistry,
  resolvePresetForIndustry,
  ROOT,
} from './lib/preset-registry.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))

const args = process.argv.slice(2)
const ifPresent = args.includes('--if-present')
const briefFlagIndex = args.indexOf('--brief')
const briefPath = resolve(
  ROOT,
  briefFlagIndex !== -1 ? args[briefFlagIndex + 1] : 'brief.json',
)

if (!existsSync(briefPath)) {
  if (ifPresent) {
    console.log('No brief.json found — skipping apply-brief')
    process.exit(0)
  }
  console.error(`Brief not found: ${briefPath}`)
  console.error('Copy brief.example.json to brief.json or pass --brief <path>')
  process.exit(1)
}

const registry = loadRegistry()
const registryIds = registry.presets.map((preset) => preset.id)

const briefSchema = z.object({
  business: z.object({
    name: z.string(),
    industry: z.string(),
    phone: z.string(),
    email: z.string().email(),
    address: z.string(),
    hours: z.string().optional(),
    tagline: z.string().optional(),
  }),
  designPreset: z.enum(registryIds).optional(),
  navigation: z.array(z.object({ label: z.string(), href: z.string() })),
  seo: z.object({
    title: z.string(),
    description: z.string(),
    keywords: z.string().optional(),
  }),
  services: z.array(
    z.object({
      slug: z.string(),
      title: z.string(),
      description: z.string(),
      icon: z.string().optional(),
    }),
  ),
  reviews: z.array(
    z.object({
      quote: z.string(),
      author: z.string(),
      rating: z.number().min(1).max(5).optional(),
    }),
  ),
  ctas: z.object({
    primary: z.object({ label: z.string(), href: z.string() }),
    secondary: z.object({ label: z.string(), href: z.string() }).optional(),
  }),
  pages: z.array(z.object({ slug: z.string(), title: z.string() })).optional(),
})

const brief = briefSchema.parse(JSON.parse(readFileSync(briefPath, 'utf8')))

let resolutionSource = 'industry-inference'
let resolvedPreset = resolvePresetForIndustry(registry, brief.business.industry)

if (brief.designPreset && registryIds.includes(brief.designPreset)) {
  resolvedPreset = brief.designPreset
  resolutionSource = 'brief'
} else if (brief.designPreset) {
  resolutionSource = 'default'
}

const presetMeta = registry.presets.find((preset) => preset.id === resolvedPreset)

const siteConfig = {
  businessName: brief.business.name,
  industry: brief.business.industry,
  tagline:
    brief.business.tagline ??
    'Licensed, insured, and available 24/7 for emergency repairs.',
  phone: brief.business.phone,
  email: brief.business.email,
  address: brief.business.address,
  hours: brief.business.hours ?? 'Mon–Fri 9am–5pm',
  designPreset: resolvedPreset,
  navigation: brief.navigation,
  primaryCta: brief.ctas.primary,
  secondaryCta: brief.ctas.secondary,
  seo: brief.seo,
  services: brief.services,
  reviews: brief.reviews,
  trustBadges: [
    { label: 'Licensed & insured', value: 'Fully licensed' },
    { label: 'Average rating', value: '4.9 ★' },
  ],
  stats: [
    { label: 'Jobs completed', value: '1,000+' },
    { label: 'Satisfaction rate', value: '98%' },
  ],
  team: [],
  faqs: [],
  serviceAreas: [],
}

const siteConfigPath = resolve(ROOT, 'src/config/site.config.ts')
const generatedAt = new Date().toISOString()

const siteConfigSource = `/**
 * AUTO-GENERATED by scripts/apply-brief.mjs — do not edit manually.
 * Source brief: ${briefPath.replace(`${ROOT}/`, '')}
 * Generated: ${generatedAt}
 */
import type { SiteConfig } from '~/config/site.types'

export const siteConfig = ${JSON.stringify(siteConfig, null, 2)} satisfies SiteConfig
`

writeFileSync(siteConfigPath, siteConfigSource)

const report = {
  generatedAt,
  briefPath: briefPath.replace(`${ROOT}/`, ''),
  briefIndustry: brief.business.industry,
  requestedPreset: brief.designPreset ?? null,
  resolvedPreset,
  resolutionSource,
  presetLabel: presetMeta?.label ?? resolvedPreset,
  presetCoverage: presetMeta?.coverage ?? 'unknown',
  presetSource: presetMeta?.source ?? 'unknown',
  htmlDataPreset: resolvedPreset,
  siteConfigPath: 'src/config/site.config.ts',
  registryPath: 'src/design/presets/registry.json',
}

const reportPath = resolve(ROOT, 'brief.applied.json')
writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`)

console.log('Applied brief successfully')
console.log(`  Brief:     ${briefPath}`)
console.log(`  Theme:     ${resolvedPreset} (${resolutionSource})`)
console.log(`  Label:     ${presetMeta?.label ?? resolvedPreset}`)
console.log(`  Coverage:  ${presetMeta?.coverage ?? 'unknown'}`)
console.log(`  Config:    src/config/site.config.ts`)
console.log(`  Report:    brief.applied.json`)
